<a href="https://colab.research.google.com/github/narsym/deep-learning-with-tensorflow-2.0/blob/master/Understanding_tensorflow_2x.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#using autograph

In [0]:
import tensorflow as tf

In [0]:
def linear_layer(x):
  return 3*x + 2

use python functions in tensorflow like this and only do this for main(useful) function

In [0]:
@tf.function
def simple_nn(x):
  return tf.nn.relu(linear_layer(x))

In [0]:
def simple_network(x):
  return 3*x

In [0]:
simple_nn

In [0]:
simple_network

<function __main__.simple_network>

#Sequential is our keras MNIST type




#Functional

In [0]:
def build_model():
  text_input_a = tf.keras.Input(shape = (None,),dtype = 'int32')
  text_input_b = tf.keras.Input(shape = (None,),dtype = 'int32')
  shared_embedding = tf.keras.layers.Embedding(1000,128)
  encoded_input_a = shared_embedding(text_input_a)
  encoded_input_b = shared_embedding(text_input_b)
  prediction_a = tf.keras.layers.Dense(1,activation = 'sigmoid',name = 'prediction_a')(encoded_input_a)
  prediction_b = tf.keras.layers.Dense(1,activation = 'sigmoid',name = 'prediction_b')(encoded_input_b)
  model = tf.keras.Model(inputs = [text_input_a,text_input_b],outputs = [prediction_a,prediction_b])
  tf.keras.utils.plot_model(model,to_file= 'shared_model.png')
build_model()

#Model Subclassing

In [0]:
class MyLayer(tf.keras.layers.Layer):
  def __init__(self,output_dim,**kwargs):
    self.output_dim = output_dim
    super(MyLayer,self).__init__()
  def build(self,input_shape):
    self.kernal = self.add_weight(name = 'kernel',shape = (input_shape[1],output_dim),initializer = 'uniform',trainable = True)
  def call(self,inputs):
    return tf.matmul(inputs,self.kernal)

In [0]:
model = tf.keras.Sequential([MyLayer(20),tf.keras.layers.Activation('softmax')])

#Callbacks

**Few callbacks**

tf.keras.callbacks.ModelCheckpoint #savemodel at regural intervals

tf.keras.callbacks.LearningRateScheduler #dynamically change learning rate during execution

tf.keras.callbacks.EarlyStopping #interupt training when validation performance degrades

tf.keras.callbacks.TensorBoard #monitor model's behaviour using tensorboard

#saving a model and weights

**save and load model**

In [0]:
model.save('my_model.h5')
model = tf.keras.model.load_model('my_model.ht')

using json

In [0]:
json_string = model.to_json()  # save 
model = tf.keras.models.model_from_json(json_string) # restore

using YAML

In [0]:
yaml_string = model.to_yaml() # save
model = tf.keras.models.model_from_yaml(yaml_string) # restore

save and load only weights

In [0]:
model.save_weights('my_model_weights.h5',save_format='h5')
model.load_weights('my_model_weights.ht')

In [16]:
import tensorflow_datasets as tfds
builders = tfds.list_builders()
print(builders)

['abstract_reasoning', 'aeslc', 'aflw2k3d', 'amazon_us_reviews', 'arc', 'bair_robot_pushing_small', 'beans', 'big_patent', 'bigearthnet', 'billsum', 'binarized_mnist', 'binary_alpha_digits', 'c4', 'caltech101', 'caltech_birds2010', 'caltech_birds2011', 'cars196', 'cassava', 'cats_vs_dogs', 'celeb_a', 'celeb_a_hq', 'cfq', 'chexpert', 'cifar10', 'cifar100', 'cifar10_1', 'cifar10_corrupted', 'citrus_leaves', 'cityscapes', 'civil_comments', 'clevr', 'cmaterdb', 'cnn_dailymail', 'coco', 'coil100', 'colorectal_histology', 'colorectal_histology_large', 'cos_e', 'curated_breast_imaging_ddsm', 'cycle_gan', 'deep_weeds', 'definite_pronoun_resolution', 'diabetic_retinopathy_detection', 'div2k', 'dmlab', 'downsampled_imagenet', 'dsprites', 'dtd', 'duke_ultrasound', 'dummy_dataset_shared_generator', 'dummy_mnist', 'emnist', 'eraser_multi_rc', 'esnli', 'eurosat', 'fashion_mnist', 'flic', 'flores', 'food101', 'gap', 'gigaword', 'glue', 'groove', 'higgs', 'horses_or_humans', 'i_naturalist2017', 'image

In [0]:
data,info = tfds.load("mnist",with_info = True)
train_data,test_data = data['train'], data['test']
print(info)

#creating dataset from numpy array

In [0]:
import numpy as np
num_items = 100
num_list = np.arange(num_items)
num_list_dataset = tf.data.Dataset.from_tensor_slices(num_list)

In [19]:
num_list_dataset

<TensorSliceDataset shapes: (), types: tf.int64>

#download and use existing datasets

In [20]:
datasets, info = tfds.load('imdb_reviews',with_info = True,as_supervised = True)
train_dataset = datasets['train']
train_dataset = train_dataset.batch(5).shuffle(50).take(2)
for data in train_dataset:
  print(data)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteS60L46/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteS60L46/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteS60L46/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.
(<tf.Tensor: shape=(5,), dtype=string, numpy=
array([b'This is the first Guinea Pig film from Japan and this is the sickest, in my opinion. A bunch of guys torture a girl for several days before finally killing her. And at this point, I will say that these films are NOT real! They are faked horror films which try to be as realistic as possible.<br /><br />The scenes are sickening but also unrealistic in many cases. For example, when they kick the girl in the floor, we can clearly see how they kick and stump the floor near the girl! And how stupid this looks! The sound effects are also unrealistic and don\'t make sense. Other scenes include animal intestines thrown on the girl, the girl exposed to loud noises for many hours, the ripping off of fingernails, worms placed on the wounds in the girl\'s body, the eye pierced and mutilated in horrific 

**Dataset is a library for dealing with input data in a principled way.**

1. Creation


*   from_tensor_slices()
*   from_tensors()
*   from_generators



2. Transformation

*  batch()
*  repeat()
*  shuffle()
*  map()
*  filter()

3. Iterators

*  next_batch = iterator.get_next()

#Mnist implemation using Estimators

In [0]:
BUFFER_SIZE = 10000
BATCH_SIZE = 64

def input_fn(mode):
  datasets, info = tfds.load(name='mnist',
                                with_info=True,
                                as_supervised=True)
  mnist_dataset = (datasets['train'] if mode == tf.estimator.ModeKeys.TRAIN else
                   datasets['test'])

  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

  return mnist_dataset.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

In [29]:
train = input_fn(tf.estimator.ModeKeys.TRAIN)
test = input_fn('test')
print(test)
print(train)

<DatasetV1Adapter shapes: ((None, 28, 28, 1), (None,)), types: (tf.float32, tf.int64)>
<DatasetV1Adapter shapes: ((None, 28, 28, 1), (None,)), types: (tf.float32, tf.int64)>


In [0]:
tf.estimator.train_and_evaluate(Classifier,train_spec=tf.estimator.TrainSpec(input_fn = input_fn),eval_spec = tf.estimator.EvalSpec(input_fn = input_fn))

**Ragged Tensor** more efficient than padding(non uniform dim tensor)

In [0]:
ragged = tf.ragged.constant([[1,2,3],[3,4,5,6,],[1,2,3,4,5]])

In [32]:
ragged

<tf.RaggedTensor [[1, 2, 3], [3, 4, 5, 6], [1, 2, 3, 4, 5]]>

#Custom training

1. GradientTape (records operations of automatic differentiation)

In [36]:
x = tf.constant([4.0])
with tf.GradientTape(persistent=True) as g:
  g.watch(x)
  y = x * x
  z = y * y
dz_dx = g.gradient(z,x)
dy_dx = g.gradient(y,x)
print(dy_dx,dz_dx)
del g

tf.Tensor([8.], shape=(1,), dtype=float32) tf.Tensor([256.], shape=(1,), dtype=float32)


2. tf.gradient_function() : computes gradients with respect to input parameter with arguments.

3. tf.value_and_gradient_function() : returns the value from the input function in addition to the list of derivatives of the input function with respect to its arguments.

4. tf.implicit_gradients() :  computes the gradients of the outputs of the input function with regards to all trainable variables these outputs depend on.

#skeleton for custom gradient

In [0]:
@tf.function
def train_step(inputs, labels):  
  with tf.GradientTape() as tape:    
    predictions = model(inputs, training=True)    
    regularization_loss = // TBD according to the problem     
    pred_loss = // TBD according to the problem    
    total_loss = pred_loss + regularization_loss  
gradients = tape.gradient(total_loss, model.trainable_variables)  
optimizer.apply_gradients(zip(gradients, model.trainable_variables))

In [0]:
for epoch in range(NUM_EPOCHS):  
  for inputs, labels in train_data:    
    train_step(inputs, labels)  
    print("Finished epoch", epoch)

#Using TensorFlow 2.x effectively

2.x Native code should follow a number of best practices:

1. Default to higher-level APIs such as tf.keras (or in certain situations, Estimators) and avoid lower-level APIs with direct computational graph manipulation unless needed for custom operations. So, in general, no tf.Session, tf.Session.run.

2. Add a tf.function decorator to make it run efficiently in graph mode with AutoGraph. Only use tf.function to decorate high-level computations; all functions invoked by high-level computations are automatically annotated on your behalf. In this way, you get the best of both worlds: high-level APIs with eager support, and the efficiency of computational graphs.

3. Use Python objects to track variables and losses. So, be Pythonic and use tf.Variable instead of tf.get_variable. In this way, variables will be treated with the normal Python scope.

4. Use tf.data datasets for data inputs and provide these objects directly to tf.keras.Model.fit. In this way, you will have a collection of high-performance classes for manipulating data and will adopt the best way to stream training data from disk.

5. Use tf.layers modules to combine predefined "lego bricks" whenever it is possible, either with Sequential or Functional APIs, or with Subclassing. Use Estimators if you need to have production-ready models, in particular if these models need to scale on multiple GPUs, CPUs, or on multiple servers. When needed, consider converting a tf.keras model into an Estimator.

6. Consider using a distribution strategy across GPUs, CPUs, and multiple servers. With tf.keras it is easy.


#Summary

  • tf.data can be used to load models in a very efficient way.

  • tf.keras and Estimators are high-level libraries where the power of   TensorFlow 1.x is still accessible via tf.* lower-level libraries. tf.keras supports eager computation while still retaining the performance of lower-level computational graphs via tf.function. tf.hub is a nice collection of pretrained models that can be used immediately.

  • Distribution Strategies allow training to be run on CPUs, GPUs, and TPUs.

  • SavedModel can be served on multiple platforms


